### ISSUE TITLE
Wrong marker placement

### ISSUE THREAD

**Issue by sikmir** [tumic0/QtPBFImagePlugin#5]
### Steps to reproduce
```sh
$ cat << EOF > test.gpx
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<gpx xmlns="http://www.topografix.com/GPX/1/1" creator="" version="1.1">
  <wpt lat="49.797098" lon="86.567346">
    <name>4436 m</name>
  </wpt>
</gpx>
EOF
$ crudini --set ~/.config/gpxsee/gpxsee.conf Map map MapTiler
$ curl -o ~/.local/share/gpxsee/style/style.json https://raw.githubusercontent.com/openmaptiles/klokantech-terrain-gl-style/master/style.json
$ gpxsee test.gpx
```

### Actual behaviour
![scr1](https://user-images.githubusercontent.com/688044/66723200-fcd8b180-ee1e-11e9-879f-6d214eb68de9.jpg)
1 - actual summit location
2 - displayed summit location

```sh
$ sed -i 's#{name:latin}\\\n##g' ~/.local/share/gpxsee/style/style.json
```
![scr3](https://user-images.githubusercontent.com/688044/66723604-cc474680-ee23-11e9-8b37-0e8fede6d9f3.jpg)

### Expected behaviour
The marker's position coincides with actual location:
![scr2](https://user-images.githubusercontent.com/688044/66723308-0ca4c580-ee20-11e9-96a7-3942f7025d5a.jpg)

### Configuration
GPXSee: 7.15
QtPBFImagePlugin: 2.0

**Comment by tumic0** [comment]
The style uses a hack:
```json
"text-anchor": "bottom"
"text-field": "{name:latin} {name:nonlatin}\n{ele} m\n▲"
```
to draw the summit "icon". The logic of the text anchor in QtPBFImagePlugin is that it aligns to the icon (if any) which is placed on the item position. If there is no icon, the text is centered on the position.

The Mapbox style specification is not 100% clear what the anchor is and how to handle the icon when there is one. But obviously the Mapbox logic is different. For icons with text (the usual case)  QtPBFImagePlugin renders the text/icon AFAIK as expected, so the motivation to change the logic because of a style that uses a hack to avoid a sprite is quiet low for me...
