### ISSUE TITLE
Can't draw water layer on maptiler pbf tiles

### ISSUE THREAD

**Issue by rusproger** [tumic0/QtPBFImagePlugin#8]
I use this code to convert vector tiles to png image:

```
    QImage *_image = new QImage();
    QString _file("C:\\z0_x0_y0.pbf");

    QImageReader _reader(_file, QString("0").toLatin1());

    //_reader.setScaledSize(QSize(256, 256));
    if (_reader.read(_image))
    {
        _image->save(_file+".png","PNG");

    }
    delete _image;
```
The received image does not contain water layer.
The visibility Layout property is not parsed?
[style.zip](https://github.com/tumic0/QtPBFImagePlugin/files/4774472/style.zip)

**Comment by tumic0** [comment]
Visibility layout property was indeed not parsed (I have added it in 9772c2f67ff1221af1e317d81fd5cd8616a3c64e), but that is not your problem. The problem is, you do not have the water source layers in your PBF file. The plugin does not download anything, all data must be in the PBF file.

(your data contains only the "globallandcover" layer)
